version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Installing Requirements
          command: |
            sed -e 's;^#http\(.*\)/v3.9/community;http\1/v3.9/community;g' -i /etc/apk/repositories
            apk add --no-cache --update \
            bash \
            build-base \
            bzip2-dev \
            curl \
            figlet \
            gcc \
            git \
            sudo \
            util-linux \
            chromium \
            chromium-chromedriver \
            jpeg-dev \
            libffi-dev \
            libpq \
            libwebp-dev \
            libxml2 \
            libxml2-dev \
            libxslt-dev \
            linux-headers \
            musl \
            neofetch \
            openssl-dev \
            php-pgsql \
            postgresql \
            postgresql-client \
            postgresql-dev \
            py-lxml \
            py-pillow \
            py-pip \
            py-requests \
            py-sqlalchemy \
            py-tz \
            py3-aiohttp \
            python-dev \
            openssl \
            pv \
            jq \
            wget \
            python3 \
            python3-dev \
            readline-dev \
            sqlite \
            sqlite-dev \
            sudo \
            zlib-dev
      - run:
          name: tes
          command: |
            pip3 install --upgrade pip setuptools
            apk --no-cache add build-base
            apk --no-cache add postgresql-dev
            python3 -m pip install psycopg2
            git clone https://github.com/legenhand/Nana-Bot.git /root/nana
            cd /root/nana
            cp /root/nana/nana/config.example.py /root/nana/nana/config.py
            python3 -m nana
